<a href="https://www.kaggle.com/code/avtnshm/my-coding-cookbook2-encoding-ml-algos?scriptVersionId=151621136" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("train.csv")
df

PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0001_01     Europa     False     B/0/P    TRAPPIST-1e  39.0  False   
1        0002_01      Earth     False     F/0/S    TRAPPIST-1e  24.0  False   
2        0003_01     Europa     False     A/0/S    TRAPPIST-1e  58.0   True   
3        0003_02     Europa     False     A/0/S    TRAPPIST-1e  33.0  False   
4        0004_01      Earth     False     F/1/S    TRAPPIST-1e  16.0  False   
...          ...        ...       ...       ...            ...   ...    ...   
8688     9276_01     Europa     False    A/98/P    55 Cancri e  41.0   True   
8689     9278_01      Earth      True  G/1499/S  PSO J318.5-22  18.0  False   
8690     9279_01      Earth     False  G/1500/S    TRAPPIST-1e  26.0  False   
8691     9280_01     Europa     False   E/608/S    55 Cancri e  32.0  False   
8692     9280_02     Europa     False   E/608/S    TRAPPIST-1e  44.0  False   

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0             0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1           109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2            43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3             0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4           303.0       70.0         151.0   565.0     2.0  Willy Santantines   
...           ...        ...           ...     ...     ...                ...   
8688          0.0     6819.0           0.0  1643.0    74.0  Gravior Noxnuther   
8689          0.0        0.0           0.0     0.0     0.0    Kurta Mondalley   
8690          0.0        0.0        1872.0     1.0     0.0       Fayey Connon   
8691          0.0     1049.0           0.0   353.0  3235.0   Celeon Hontichre   
8692        126.0     4688.0           0.0     0.0    12.0   Propsh Hontichre   

      Transported  
0           False  
1            True  
2           False  
3           False  
4            True  
...           ...  
8688        False  
8689        False  
8690         True  
8691        False  
8692         True  

[8693 rows x 14 columns]

In [2]:
for col in df.columns:
    df[col].fillna("NA" if df[col].dtype == 'O' else df[col].mean(), inplace=True)

# Encoding

In [5]:
from sklearn.preprocessing import LabelEncoder
import category_encoders as ce
categorical_cols = df.select_dtypes(include='object').columns
object_cols = df[categorical_cols].select_dtypes(include=['object']).columns
not_encoded_cols = []

df[object_cols] = df[object_cols].astype(str)

bool_cols = df.select_dtypes(include=bool).columns
df[bool_cols] = df[bool_cols].astype(str)


for col in object_cols:
    unique_categories = df[col].nunique()

    if unique_categories <= 7:
        label_encoder = LabelEncoder()
        df[col] = label_encoder.fit_transform(df[col])
        print(f"{col} (Label Encoded): {df[col].nunique()} unique categories")
    elif 7 < unique_categories <= 15:
        ordinal_encoder = ce.OrdinalEncoder(cols=[col], handle_unknown='return_nan')
        df[col] = ordinal_encoder.fit_transform(df[col])
        print(f"{col} (Ordinal Encoded): {df[col].nunique()} unique categories")
    else:
        not_encoded_cols.append(col)
        print(f"{col} has more than 15 unique categories and won't be encoded.")
print("Not Encoded Columns:", not_encoded_cols)

PassengerId has more than 15 unique categories and won't be encoded.

Cabin has more than 15 unique categories and won't be encoded.

Name has more than 15 unique categories and won't be encoded.

Transported (Label Encoded): 2 unique categories

Not Encoded Columns: ['PassengerId', 'Cabin', 'Name']


### Code is correct, run twice to double check

In [6]:
df.dtypes

PassengerId      object
HomePlanet        int32
CryoSleep         int32
Cabin            object
Destination       int32
Age             float64
VIP               int32
RoomService     float64
FoodCourt       float64
ShoppingMall    float64
Spa             float64
VRDeck          float64
Name             object
Transported       int32
dtype: object

In [7]:
df = df.drop(columns=not_encoded_cols)


In [8]:
df

HomePlanet  CryoSleep  Destination   Age  VIP  RoomService  FoodCourt  \
0              1          0            3  39.0    0          0.0        0.0   
1              0          0            3  24.0    0        109.0        9.0   
2              1          0            3  58.0    2         43.0     3576.0   
3              1          0            3  33.0    0          0.0     1283.0   
4              0          0            3  16.0    0        303.0       70.0   
...          ...        ...          ...   ...  ...          ...        ...   
8688           1          0            0  41.0    2          0.0     6819.0   
8689           0          2            2  18.0    0          0.0        0.0   
8690           0          0            3  26.0    0          0.0        0.0   
8691           1          0            0  32.0    0          0.0     1049.0   
8692           1          0            3  44.0    0        126.0     4688.0   

      ShoppingMall     Spa  VRDeck  Transported  
0              0.0     0.0     0.0            0  
1             25.0   549.0    44.0            1  
2              0.0  6715.0    49.0            0  
3            371.0  3329.0   193.0            0  
4            151.0   565.0     2.0            1  
...            ...     ...     ...          ...  
8688           0.0  1643.0    74.0            0  
8689           0.0     0.0     0.0            0  
8690        1872.0     1.0     0.0            1  
8691           0.0   353.0  3235.0            0  
8692           0.0     0.0    12.0            1  

[8693 rows x 11 columns]

In [9]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (8693, 10)

Shape of y: (8693,)


# Random Number Search

In [13]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LogisticRegression

best_random_state = None
best_test_accuracy = -1

for i in range(1, 12):  # Iterating through numbers 1-11
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=i)
    model = LogisticRegression()  
    model.fit(X_train, y_train)
    
    train_accuracy = model.score(X_train, y_train)
    test_accuracy = model.score(X_test, y_test)
    cv_accuracy = cross_val_score(model, X, y, cv=5, scoring='accuracy').mean()
    
    if abs(train_accuracy - test_accuracy) <= 0.05 and abs(test_accuracy - cv_accuracy) <= 0.05:
        print(f"Random State: {i}, Test Accuracy: {test_accuracy:.4f}, Train-CV Diff: {abs(train_accuracy - cv_accuracy):.4f}")
        
        
        if test_accuracy > best_test_accuracy:
            best_test_accuracy = test_accuracy
            best_random_state = i

print("Best Random State Number:", best_random_state)


Random State: 1, Test Accuracy: 0.7844, Train-CV Diff: 0.0016

Random State: 2, Test Accuracy: 0.7878, Train-CV Diff: 0.0017

Random State: 3, Test Accuracy: 0.7729, Train-CV Diff: 0.0013

Random State: 4, Test Accuracy: 0.7803, Train-CV Diff: 0.0000

Random State: 5, Test Accuracy: 0.7815, Train-CV Diff: 0.0029

Random State: 6, Test Accuracy: 0.7815, Train-CV Diff: 0.0027

Random State: 7, Test Accuracy: 0.7964, Train-CV Diff: 0.0006

Random State: 8, Test Accuracy: 0.7982, Train-CV Diff: 0.0056

Random State: 9, Test Accuracy: 0.7602, Train-CV Diff: 0.0039

Random State: 10, Test Accuracy: 0.7792, Train-CV Diff: 0.0030

Random State: 11, Test Accuracy: 0.7959, Train-CV Diff: 0.0012

Best Random State Number: 8


### Random number search for Regression, in a markdwon cell

import warnings
warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LinearRegression

best_random_state = None
best_test_score = -1

for i in range(12, 21):  # Increase the numbers as need
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=i)
    model = LinearRegression() #Change for classification
    model.fit(X_train, y_train)
    
    train_score = model.score(X_train, y_train)
    test_score = model.score(X_test, y_test)
    cv_score = cross_val_score(model, X, y, cv=5).mean()
    
    if abs(train_score - test_score) <= 0.05 and abs(test_score - cv_score) <= 0.05:
        print(f"Random State: {i}, Test Score: {test_score:.4f}, Train-CV Diff: {abs(train_score - cv_score):.4f}")
        
        
        if test_score > best_test_score:
            best_test_score = test_score
            best_random_state = i

print("Best Random State Number:", best_random_state)


# Classification Algorithm with best accuracy

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=8)

# List of classification models
models = [
    ('Logistic Regression', LogisticRegression()),
    ('Decision Tree', DecisionTreeClassifier()),
    ('Random Forest', RandomForestClassifier()),
    ('Support Vector Machine', SVC())
]

best_model_name = None
best_accuracy = -1

for name, model in models:
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    accuracy = accuracy_score(y_test, y_pred)
    
    print(f'{name}:')
    print(f'Accuracy: {accuracy:.4f}')
    
    if accuracy > best_accuracy:
        best_accuracy = accuracy
        best_model_name = name

    print(f'Precision: {precision_score(y_test, y_pred):.4f}')
    print(f'Recall: {recall_score(y_test, y_pred):.4f}')
    print(f'F1 Score: {f1_score(y_test, y_pred):.4f}')
    print(f'Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n{"-"*30}\n')

print(f'The best model is: {best_model_name} with an accuracy of {best_accuracy:.4f}')


Logistic Regression:

Accuracy: 0.7982

Precision: 0.8156

Recall: 0.7932

F1 Score: 0.8042

Confusion Matrix:

[[667 163]

 [188 721]]

------------------------------



Decision Tree:

Accuracy: 0.7401

Precision: 0.7454

Recall: 0.7635

F1 Score: 0.7543

Confusion Matrix:

[[593 237]

 [215 694]]

------------------------------



Random Forest:

Accuracy: 0.7838

Precision: 0.8110

Recall: 0.7646

F1 Score: 0.7871

Confusion Matrix:

[[668 162]

 [214 695]]

------------------------------



Support Vector Machine:

Accuracy: 0.8016

Precision: 0.7743

Recall: 0.8757

F1 Score: 0.8219

Confusion Matrix:

[[598 232]

 [113 796]]

------------------------------



The best model is: Support Vector Machine with an accuracy of 0.8016


### Regression Algorithm with best accuracy in a markdown cell

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler
import numpy as np

data = {'X1': [1, 2, 3, 4, 5], 'X2': [5, 4, 3, 2, 1], 'y': [10, 20, 30, 40, 50]}
df = pd.DataFrame(data)

X = df[['X1', 'X2']]
y = df['y']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

models = [
    ('Linear Regression', LinearRegression()),
    ('Ridge Regression', Ridge()),
    ('Lasso Regression', Lasso()),
    ('Random Forest Regressor', RandomForestRegressor())
]

best_model_name = None
best_r2 = -np.inf

for name, model in models:
    try:
        
        model.fit(X_train, y_train)
        y_pred_train = model.predict(X_train)
        y_pred_test = model.predict(X_test)

        mse_train = mean_squared_error(y_train, y_pred_train)
        mse_test = mean_squared_error(y_test, y_pred_test)
        r2 = r2_score(y_test, y_pred_test)
        rmse = np.sqrt(mse_test)

        cv_score = cross_val_score(model, X_train, y_train, cv=4, scoring='neg_mean_squared_error').mean()

        print(f'{name}:')
        print(f'Train Mean Squared Error: {mse_train:.2f}')
        print(f'Test Mean Squared Error: {mse_test:.2f}')
        print(f'Test R-squared (R2): {r2:.2f}')
        print(f'Test Root Mean Squared Error (RMSE): {rmse:.2f}')
        print(f'Cross-Validated Mean Squared Error: {cv_score:.2f}\n')

        if r2 > best_r2:
            best_r2 = r2
            best_model_name = name

    except Exception as e:
        print(f'Error with model {name}: {str(e)}')

print(f'Best Model: {best_model_name} with R-squared (R2): {best_r2:.2f}')
